### ISSUE TITLE
There are some things in the code that I don’t understand

### ISSUE THREAD

**Issue by peplee123** [jimmyc96/spectral-dis-FL#1]
Lines 130 and 131 in update.py under util,
spec_w = spectral_cal(net,input=True)
spec_l = spectral_cal(net_glob,input=False)
Why is the input of spec_l False? I am a little confused and hope to get an answer. Shouldn't we ensure that the two operations are the same before we can calculate KL?

**Comment by jimmyc96** [comment]
Thanks for your feedback! You are right. The argument is not aligned, which was caused during code testing before I released the code. I will revise it in the updated version.  You can use the code with both argument be True.

**Comment by jimmyc96** [comment]
Thanks for your feedback! You are right. The argument is not aligned, which was caused during code testing before I released the code. I will revise it in the updated version. You can use the code with both arguments to be the same.
