### ISSUE TITLE
Calculation time: really slow in my own laptop

### ISSUE THREAD

**Issue by Qunean** [jimmyc96/spectral-dis-FL#2]
Hi, I follow the instruction, but the training seems like really slow on my laptop. I am concerned that the computing time is mainly spent on spectral transferring rather than back propagate. It's that right ? 

Restnet18 cifar10 and batch_sz=64. every epoch cost about 20min?

**Comment by jimmyc96** [comment]
Hi, yes. The spectral-related computation is the key component in the overall training process. The time highly depends on the GPUs that you use. You can also try some acceleration techniques on that, such as parallel training, etc.
