### ISSUE TITLE
The detail of calculation of spectrum.

### ISSUE THREAD

**Issue by Qunean** [jimmyc96/spectral-dis-FL#3]
I notice that in your code, you just cut the first 40% to be your low frequency spectrum while you have not shift them into right order. Can you tell me is there any specific reason about this calculation way?
Thank you .

**Comment by jimmyc96** [comment]
Hi, it's a hyperparameter, which comes from empirical intuition as cutting low-frequency features. You can try empirical tuning for each task.

**Comment by Qunean** [comment]
yes I know it's hyperparameter, and I saw your experiment details about this hyperparameter. I mean if you just do it after calculation the "np.fft.fft2(weight_tensor.cpu().numpy(), axes=[0, 1])" without something like sorting the value. Will it be the low frequency?

**Comment by jimmyc96** [comment]
This is based on our assumption. You can also try sorting-then-cutting. In our future version, we are working on this.
